### ISSUE TITLE
[bug] string with yaml tag is automatically converted to other type if possible

### ISSUE THREAD

**Issue by valentingol** [valentingol/cliconfig#32]
When a parameter is tagged with a yaml tag and contain a string that can be interpreted as an other type, this string is automatically converted to the other type:
E:g:
```yaml
config:
  param: !tag "True"
  param2: !tag "2.3"
```
It is converted to `{"config": {"param@tag": True, "param2@tag": 2.3}}`

To solve this, use cliconfig tags:
```yaml
config:
  param@tag: "True"
  param2@tag: "2.3"
```
It is converted to `{"config": {"param@tag": "True", "param2@tag": "2.3"}}`

Source of the behavior: https://github.com/valentingol/cliconfig/blob/main/cliconfig/yaml_tags/_yaml_tags.py, line 53
